// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "before-after" section.

import React from 'react';
import AboutMediaOverlay from '@/components/sections/about/AboutMediaOverlay';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function BeforeAfterSection(): React.JSX.Element {
  return (
    <div id="before-after" data-section="before-after">
        <SectionErrorBoundary name="before-after">
              <AboutMediaOverlay
        tag="Results"
        title="Before vs After"
        description="Don't settle for outdated layouts. Transform your digital presence into a conversion machine."
        imageSrc="https://picsum.photos/seed/2082052325/1200/800"
        textAnimation="fade-blur"
      />
        </SectionErrorBoundary>
      </div>
  );
}
