// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="Contact"
          text="Ready to get your new website started? Schedule a free audit today."
          primaryButton={{
            text: "Get Free Website Audit",
            href: "#contact",
          }}
          secondaryButton={{
            text: "Email Us",
            href: "mailto:hello@madenew.studio",
          }}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
