// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqTabbedAccordion from '@/components/sections/faq/FaqTabbedAccordion';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqTabbedAccordion
          tag="FAQ"
          title="Common Questions"
          description="Everything you need to know about our web design process."
          categories={[
            {
              name: "General",
              items: [
                {
                  question: "How long does it take?",
                  answer: "I deliver most projects within 24–48 hours.",
                },
                {
                  question: "Can you redesign my current website?",
                  answer: "Yes, I specialize in modernizing outdated sites.",
                },
              ],
            },
            {
              name: "Service",
              items: [
                {
                  question: "Do you provide hosting?",
                  answer: "Yes, I offer maintenance plans that include hosting support.",
                },
                {
                  question: "Can I edit the website later?",
                  answer: "Absolutely, all builds are easy to update.",
                },
              ],
            },
          ]}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
