// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroSplitMediaGrid from '@/components/sections/hero/HeroSplitMediaGrid';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroSplitMediaGrid
          tag="Made New Studio"
          title="Your Website Should Bring You Customers—Not Drive Them Away"
          description="I build beautiful, high-converting websites for local businesses in as little as 24–48 hours. Fast, modern, mobile-friendly, and built to grow your business."
          primaryButton={{
            text: "Get My Free Website Audit",
            href: "#contact",
          }}
          secondaryButton={{
            text: "See My Work",
            href: "#portfolio",
          }}
          items={[
            {
              imageSrc: "http://img.b2bpic.net/free-photo/view-3d-buttons_23-2149917545.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/medication-drug-pharmacist-prescription-patient_53876-124312.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
