// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroSplitMediaGrid from '@/components/sections/hero/HeroSplitMediaGrid';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroSplitMediaGrid
        tag="Made New Studio"
        title="Your Website Should Bring You Customers—Not Drive Them Away"
        description="I build beautiful, high-converting websites for local businesses in as little as 24–48 hours. Fast, modern, mobile-friendly, and built to grow your business."
        primaryButton={{
            text: "Get My Free Website Audit",
            href: "#contact",
          }}
        secondaryButton={{
            text: "See My Work",
            href: "#portfolio",
          }}
        items={[{"imageSrc":"https://images.unsplash.com/photo-1471922694854-ff1b63b20054?q=80&w=2072&auto=format&fit=crop"},{"imageSrc":"https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=2073&auto=format&fit=crop"}]}
        textAnimation="fade-blur"
      />
        </SectionErrorBoundary>
      </div>
  );
}
