// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsSimpleCards from '@/components/sections/metrics/MetricsSimpleCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsSimpleCards
          tag="Value"
          title="Why Choose Made New Studio"
          description="Focused on speed, results, and your long-term success."
          metrics={[
            {
              value: "24-48h",
              description: "Rapid Turnaround",
            },
            {
              value: "100%",
              description: "Mobile Optimized",
            },
            {
              value: "SEO",
              description: "Search Ready",
            },
            {
              value: "0",
              description: "Contracts",
            },
          ]}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
