// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "portfolio" section.

import React from 'react';
import FeaturesImageBento from '@/components/sections/features/FeaturesImageBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function PortfolioSection(): React.JSX.Element {
  return (
    <div id="portfolio" data-section="portfolio">
        <SectionErrorBoundary name="portfolio">
              <FeaturesImageBento
          tag="Portfolio"
          title="Recent Projects"
          description="Beautiful, high-converting sites for diverse local businesses."
          items={[
            {
              title: "Local Cafe",
              description: "Website Design",
              imageSrc: "http://img.b2bpic.net/free-photo/image-young-stylish-guy-with-laptop-sitting-cafe-with-his-computer-typing-something-drinking_1258-314318.jpg",
            },
            {
              title: "Fitness Studio",
              description: "Brand Redesign",
              imageSrc: "http://img.b2bpic.net/free-photo/vertical-shot-pensive-sporty-woman-has-fitness-training-outdoors-holds-stereo-headphones-dressed-activewear-poses-knees-karemat-modern-city-daytime-healthy-lifestyle-concept_273609-59150.jpg",
            },
            {
              title: "Architect",
              description: "Portfolio Site",
              imageSrc: "http://img.b2bpic.net/free-photo/blueprint-architect-construction-project-sketch-concept_53876-120012.jpg",
            },
            {
              title: "Boutique Shop",
              description: "E-commerce Build",
              imageSrc: "http://img.b2bpic.net/free-photo/online-shop-buy-internet-shopping-store-concept_53876-127377.jpg",
            },
            {
              title: "Law Firm",
              description: "Corporate Identity",
              imageSrc: "http://img.b2bpic.net/free-photo/business-marketing-planning-trategy-graph_53876-121052.jpg",
            },
            {
              title: "Real Estate",
              description: "Property Listings",
              imageSrc: "http://img.b2bpic.net/free-photo/3d-rendering-isometric-house_23-2150727946.jpg",
            },
            {
              title: "Coming Soon",
              description: "Stay Tuned",
              imageSrc: "http://img.b2bpic.net/free-photo/agenda-calendar-appointment-graphic-concept_53876-121111.jpg",
            },
          ]}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
