// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "portfolio" section.

import React from 'react';
import FeaturesImageBento from '@/components/sections/features/FeaturesImageBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function PortfolioSection(): React.JSX.Element {
  return (
    <div id="portfolio" data-section="portfolio">
        <SectionErrorBoundary name="portfolio">
              <FeaturesImageBento
        tag="Portfolio"
        title="Recent Projects"
        description="Beautiful, high-converting sites for diverse local businesses."
        items={[{"title":"Local Cafe","imageSrc":"https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80","description":"Website Design"},{"title":"Fitness Studio","description":"Brand Redesign","imageSrc":"https://images.unsplash.com/photo-1472214103451-9374bd1c798e?auto=format&fit=crop&q=80"},{"title":"Architect","description":"Portfolio Site","imageSrc":"https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&q=80"},{"imageSrc":"https://images.unsplash.com/photo-1495908333425-29a1e0918c5f?auto=format&fit=crop&q=80","description":"E-commerce Build","title":"Boutique Shop"},{"title":"Law Firm","description":"Corporate Identity","imageSrc":"https://images.unsplash.com/photo-1518182170546-0766de6b6aa1?auto=format&fit=crop&q=80"},{"imageSrc":"https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80","description":"Property Listings","title":"Real Estate"},{"title":"Coming Soon","imageSrc":"https://images.unsplash.com/photo-1440688807730-73e4e2169fb8?auto=format&fit=crop&q=80","description":"Stay Tuned"}]}
        textAnimation="fade"
      />
        </SectionErrorBoundary>
      </div>
  );
}
