// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "pricing" section.

import React from 'react';
import PricingHighlightedCards from '@/components/sections/pricing/PricingHighlightedCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function PricingSection(): React.JSX.Element {
  return (
    <div id="pricing" data-section="pricing">
        <SectionErrorBoundary name="pricing">
              <PricingHighlightedCards
          tag="Pricing"
          title="Transparent Pricing"
          description="Choose the perfect plan to grow your business."
          plans={[
            {
              tag: "Starter",
              price: "$500",
              description: "Perfect for small businesses needing a refresh.",
              features: [
                "5 pages",
                "Mobile optimization",
                "Contact form",
                "SEO basics",
              ],
              primaryButton: {
                text: "Get Started",
                href: "#contact",
              },
            },
            {
              tag: "Professional",
              price: "$800",
              description: "Everything in Starter plus advanced design features.",
              features: [
                "Everything in Starter",
                "Custom design",
                "Blog",
                "Google Analytics",
                "Speed optimization",
              ],
              highlight: "Recommended",
              primaryButton: {
                text: "Get Started",
                href: "#contact",
              },
            },
            {
              tag: "Premium",
              price: "Custom",
              description: "Advanced functionality for high-growth businesses.",
              features: [
                "Booking systems",
                "Memberships",
                "E-commerce",
                "Custom integrations",
              ],
              primaryButton: {
                text: "Contact Me",
                href: "#contact",
              },
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
