// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "services" section.

import React from 'react';
import FeaturesBentoGrid from '@/components/sections/features/FeaturesBentoGrid';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ServicesSection(): React.JSX.Element {
  return (
    <div id="services" data-section="services">
        <SectionErrorBoundary name="services">
              <FeaturesBentoGrid
          tag="Our Services"
          title="Designed to Grow"
          description="Comprehensive web solutions tailored for local businesses."
          features={[
            {
              title: "Website Refresh",
              description: "Modern redesign of your existing website. Includes SEO, mobile optimization, and branding updates.",
              imageSrc: "http://img.b2bpic.net/free-photo/internet-speed-test-software-concept_53876-120681.jpg",
            },
            {
              title: "New Website",
              description: "Completely custom business website. Includes contact form, Google Maps, mobile responsive, and basic SEO.",
              imageSrc: "http://img.b2bpic.net/free-photo/high-view-black-price-tag-with-shadow_23-2148629508.jpg",
            },
            {
              title: "Website Care Plan",
              description: "Monthly maintenance including hosting support, content edits, backups, and performance monitoring.",
              imageSrc: "http://img.b2bpic.net/free-photo/user-profile-icon-front-side_187299-39596.jpg",
            },
            {
              title: "SEO & Performance",
              description: "Get found on Google with optimized speed and visibility improvements.",
              imageSrc: "http://img.b2bpic.net/free-photo/internet-speed-test-software-concept_53876-124238.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
