// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "services" section.

import React from 'react';
import FeaturesBentoGrid from '@/components/sections/features/FeaturesBentoGrid';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ServicesSection(): React.JSX.Element {
  return (
    <div id="services" data-section="services">
        <SectionErrorBoundary name="services">
              <FeaturesBentoGrid
        tag="Our Services"
        title="Designed to Grow"
        description="Comprehensive web solutions tailored for local businesses."
        features={[{"title":"Website Refresh","description":"Modern redesign of your existing website. Includes SEO, mobile optimization, and branding updates.","imageSrc":"https://images.unsplash.com/photo-1495908333425-29a1e0918c5f?auto=format&fit=crop&q=80"},{"title":"New Website","description":"Completely custom business website. Includes contact form, Google Maps, mobile responsive, and basic SEO.","imageSrc":"https://images.unsplash.com/photo-1506744626753-dba37c259d1b?auto=format&fit=crop&q=80"},{"description":"Monthly maintenance including hosting support, content edits, backups, and performance monitoring.","title":"Website Care Plan","imageSrc":"https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80"},{"description":"Get found on Google with optimized speed and visibility improvements.","title":"SEO & Performance","imageSrc":"https://images.unsplash.com/photo-1440688807730-73e4e2169fb8?auto=format&fit=crop&q=80"}]}
        textAnimation="slide-up"
      />
        </SectionErrorBoundary>
      </div>
  );
}
