// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "social-proof" section.

import React from 'react';
import SocialProofMarquee from '@/components/sections/social-proof/SocialProofMarquee';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function SocialProofSection(): React.JSX.Element {
  return (
    <div id="social-proof" data-section="social-proof">
        <SectionErrorBoundary name="social-proof">
              <SocialProofMarquee
          tag="Trust"
          title="Trusted by Local Businesses"
          description="Building brands that scale across all digital platforms."
          names={[
            "TechCorp",
            "InnovateLab",
            "GrowthCo",
            "StartupXYZ",
            "LocalBistro",
            "PeakFitness",
            "StyleDesign",
          ]}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
